client = pymongo.MongoClient()
dbname = client['capstone']
filename_collection = dbname['filename']
filename_collection.insert_one({
    "name":filename
})

filedata_collection = dbname['filecontent']
filedata = {
                "un_name" : un_name,
                "faculty_name" : faculty_name,
                "program" : programme,
                "branch" : branch,
                "semester" : semester,
                "version" : version,
                "effective_academic_year" : effective_academic_year,
                "effective_for_batch" : effective_for_batch,
                "subject_code" : subject_code,
                "subject_name" : subject_name,
                "lecture_credits" : lc,
                "tutorial_credits" : tuc,
                "practical_credits" : pc,
                "twc" : twc,
                "total_credits" : totalc,
                "lecture_hours" : lh,
                "tutorial_hours" : tuh,
                "practical_hours" : ph,
                "twh" : twh,
                "total_hours" : totalh,
                "ce_theory" : cet,
                "see_theory" : seet,
                "total_theory" : totalt,
                "ce_prctical" : cep,
                "see_practical" : seep,
                "total_practical" : totalp,
                "pre_requsites" : pre_requsites,
                "CO1" : CO1,
                "CO2" : CO2,
                "CO3" : CO3,
                "CO4" : CO4,
                "CO5" : CO5,
                "CO6" : CO6,
                "C1P1" : C1P1, 
                "C1P2" : C1P2,
                "C1P3" : C1P3, 
                "C1P4" : C1P4,
                "C1P5" : C1P5, 
                "C1P6" : C1P6, 
                "C1P7" : C1P7, 
                "C1P8" : C1P8, 
                "C1P9" : C1P9, 
                "C1P10" : C1P10,
                "C1P11" : C1P11,
                "C1P12" : C1P12,
                "C2P1" :C2P1, 
                "C2P2" :C2P2,
                "C2P3" :C2P3,
                "C2P4" :C2P4,
                "C2P5" :C2P5,
                "C2P6" :C2P6,
                "C2P7" :C2P7,
                "C2P8" :C2P8,
                "C2P9" :C2P9,
                "C2P10" :C2P10,
                "C2P11" :C2P11,
                "C2P12" :C2P12,
                "C3P1": C3P1, 
                "C3P2": C3P2,
                "C3P3": C3P3,
                "C3P4": C3P4,
                "C3P5": C3P5,
                "C3P6": C3P6,
                "C3P7": C3P7,
                "C3P8": C3P8,
                "C3P9": C3P9,
                "C3P10": C3P10,
                "C3P11": C3P11,
                "C3P12": C3P12,
                "C4P1":C4P1, 
                "C4P2":C4P2, 
                "C4P3":C4P3, 
                "C4P4":C4P4, 
                "C4P5":C4P5, 
                "C4P6":C4P6, 
                "C4P7":C4P7, 
                "C4P8":C4P8, 
                "C4P9":C4P9, 
                "C4P10":C4P10,
                "C4P11":C4P11,
                "C4P12":C4P12,
                "C5P1":C5P1,
                "C5P2":C5P2, 
                "C5P3":C5P3, 
                "C5P4":C5P4, 
                "C5P5":C5P5, 
                "C5P6":C5P6, 
                "C5P7":C5P7, 
                "C5P8":C5P8, 
                "C5P9":C5P9, 
                "C5P10":C5P10,
                "C5P11":C5P11,
                "C5P12":C5P12,
                "C6P1":C6P1, 
                "C6P2":C6P2, 
                "C6P3":C6P3, 
                "C6P4":C6P4, 
                "C6P5":C6P5, 
                "C6P6":C6P6, 
                "C6P7":C6P7, 
                "C6P8":C6P8, 
                "C6P9":C6P9, 
                "C6P10":C6P10,
                "C6P11":C6P11,
                "C6P12":C6P12
            }

SQLITE
                # try:
            #     chk_file = files.objects.get(filename = f'{subject_code}{subject_name}')
            # except files.DoesNotExist:
            #     new_file = files(filename = f'{subject_code}{subject_name}')
            #     new_file.save()